### ISSUE TITLE
Error loading checkpoint

### ISSUE THREAD

**Issue by TalalWasim** [jy0205/STCAT#6]
Hi,

I am having trouble when evaluating pretrained checkpoint. I get the following error:

**RuntimeError: Error(s) in loading state_dict for STCATNet:
        size mismatch for ground_encoder.encoder.time_embed.te: copying a param with shape torch.Size([301, 1, 256]) from checkpoint, the shape in current model is torch.Size([201, 1, 256]).**

**Comment by yoon28** [comment]
+1

**Comment by yoon28** [comment]
@jy0205 How can I resolve this problem?

**Comment by yoon28** [comment]
@TalalWasim 
I finally figured it out.
Set `INPUT.MAX_VIDEO_LEN` to `300` when you execute the code.
