### ISSUE TITLE
Dataset link invalid

### ISSUE THREAD

**Issue by PhoenixZ810** [jy0205/STCAT#9]
Thanks for you great contribution! The links of Beida NetDisk of VidSTG and HCSTVG are invalid, can you please release a new link?

**Comment by Joddy-23** [comment]
I also have the same issue. The trained checkpoints of  VidSTG and HCSTVG you shared are invalid. I would like to ask if it is possible to  release a new valid link.

**Comment by zohrehghaderi** [comment]
Me too

**Comment by jy0205** [comment]
We have updated the data link.

**Comment by Joddy-23** [comment]
Thank you very much!

**Comment by sximasth** [comment]
The links of Beida NetDisk of the bounding-box annotations of VidSTG are invalid now, can you please release a new link again?

**Comment by jy0205** [comment]
The URL still works? https://disk.pku.edu.cn/link/AA9BD598C845DC43A4B6A0D35268724E4B

**Comment by sximasth** [comment]
Thank you！
